# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kio': '@latest'
    'libraries/polkit-qt-1': '@latest'

- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'libraries/polkit-qt-1': '@latest-kf6'
